[package]
name = "keyberon"
version = "0.1.0"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>", "Robin Krahl <robin.krahl@ireas.org>"]
edition = "2018"

[dependencies]
either = { version = "1.5", default-features = false }
generic-array = "0.13"
embedded-hal = "0.2"
usb-device = "0.2.0"
heapless = "0.5"

[dev-dependencies]
void = { version = "1", default-features = false }
stm32f1xx-hal = { version = "0.4", features = ["rt", "stm32f103" ] }
cortex-m = "0.6"
cortex-m-rt = { version = "0.6.6", features = ["device"] }
panic-semihosting = "0.5"
stm32-usbd = { version = "0.4.0", features = ["stm32f103xx"] }
cortex-m-rtfm = "0.4.1"
cortex-m-semihosting = "0.3.2"

[profile.dev]
opt-level = 1
lto = true
incremental = false

[profile.release]
lto = true
incremental = false
opt-level = "z"
debug = true
